apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymongo  # Adjust name if needed
spec:
  replicas: 1  # Specify desired number of replicas (default is 1)
  selector:
    matchLabels:
      app: mymongo
  template:
    metadata:
      labels:
        app: mymongo
    spec:
      containers:
      - name: mymongo
        image: mongo:latest  # Provide specific image name or tag
        ports:
        - containerPort: 27017