apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: mymongo
spec:
  template:
    metadata:
      labels:
        app: mymongo
    spec:
      containers:
      - name: mymongo
        image: mymongo
        ports:
        - containerPort: 27017
