apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-stack
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: full-stack
    spec:
      containers:
      - name: full-stack
        image: sanjeevashwin/kube
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_URI
            value: 'mongodb://mymongo:27017/full-stack'
    
