apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-stack  # Adjust name if needed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: full-stack
  template:
    metadata:
      labels:
        app: full-stack
    spec:
      containers:
      - name: full-stack
        image: sanjeevashwin/fullstack
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: 'mongodb://mymongo:27017/full-stack'
