apiVersion: v1
kind: Service
metadata:
  name: full-stack
  labels:
    app: full-stack
spec:
  selector:
    app: full-stack
  ports:
    - port: 5000
      protocol: TCP
      nodePort: 30061
  type: LoadBalancer
